# -*- coding: utf-8 -*-
"""Seasonal_Agriculture_Performance_Analysis_Data_Analytics_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yur06ce2ptNclsfBvIoDySZklfheL6xE

**Project Name: Seasonal Agriculture Performance Analysis**

        Major Project- Data Analytics

Domain: Agriculture

Project Theme: Seasonal Agriculture Performance Analysis.

Tools and Technologies:


Python

pandas

Numpy

Matplotlib

Seaborn

**Problem Statement**

Agricultural activities are influenced by seasonal variations in environmental conditions,
farming practices, resource availability and market conditions. As a result, agricultural
performance may differ from one season to another.
However, raw agricultural data does not clearly explain how agricultural performance changes
across seasons or what patterns can be observed in different seasonal conditions.

The problem is to analyze the given agricultural dataset and investigate seasonal differences
in agricultural performance by identifying meaningful patterns, trends, relationships and
variations within the available data.

**Project Objective**

To analyze agricultural data across different seasons, identify variations in farming performance, discover important trends and patterns, and generate meaningful insights that help in understanding seasonal agricultural outcomes.


To analyze agricultural performance across different seasons.

To identify seasonal patterns and changes in agricultural activities.

To compare agricultural outcomes between different seasons.

To examine relationships between important factors in the dataset.

To discover meaningful trends and variations using data analysis.

To present the findings through clear and informative visualizations.

To derive useful insights from the available agricultural data.

**Project Description**


Seasonal Agriculture Performance Analysis is a data analytics project that studies agricultural performance across different seasons and farming conditions. The project analyzes factors such as environmental conditions, farming practices, resource usage, crop production, and economic performance to identify meaningful patterns, trends, relationships, and differences. The insights obtained from the analysis help in understanding seasonal agricultural performance and support better agricultural planning.

**Dataset**

The dataset represents agricultural activities carried out across different seasons,
geographical areas and farming conditions. It contains information related to farming
practices, environmental conditions, crop production, resource usage and economic
performance.
The dataset provides students with an opportunity to explore how agricultural performance
changes across seasons and to identify meaningful patterns and differences through data
analysis.

Dataset File Name:
Seasonal_Agricultural_Performance_dataset.csv
"""

# Commented out IPython magic to ensure Python compatibility.
# Import required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", None)

pd.set_option("display.float_format", lambda x: f"{x:.2f}")

# Loading the Dataset
df=pd.read_csv("/content/seasonal_agriculture_performance_dataset.csv")
print("Dataset Loaded Successfully.")

# First 5 rows
df.head()

# last 5 rows
df.tail()

# Number of columns and shape
df.shape

# Column Names
print(df.columns.tolist())

# column names
df.columns

# Dataset Information
df.info()

# Missing Values Check
df.isnull().sum()

# Handle missing values

numeric_columns = df.select_dtypes(include='number').columns
categorical_columns = df.select_dtypes(include='object').columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

for col in categorical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("Total missing values after handling:",
      df.isnull().sum().sum())

# Duplicate rows check
df.duplicated().sum()

# Number of unique values in each column

print(df.nunique())

# Statistical Information
df.describe()

print(df.columns.tolist())

# Display basic information about categorical columns

print("Unique Seasons:")
print(df["Season"].unique())

print("\nUnique Crops:")
print(df["Crop"].unique())

print("\nUnique States:")
print(df["State"].unique())

# Check columns with missing values

missing = df.isnull().sum()

missing = missing[missing > 0]

if len(missing) == 0:
    print("No missing values found in the dataset.")
else:
    print("Columns with missing values:")
    print(missing)

# Remove duplicate records

before = df.shape[0]

df = df.drop_duplicates()

after = df.shape[0]

print("Duplicate records removed:", before - after)
print("Dataset shape after removing duplicates:", df.shape)

# Check data types of all columns
print(df.dtypes)

"""**EDA**

1. Season Distribution Graph
"""

# Season-wise Distribution of Agricultural Records

plt.figure(figsize=(10, 6))

season_counts = df["Season"].value_counts()

bars = plt.bar(
    season_counts.index,
    season_counts.values,
    color=["Red", "Green", "Blue", "Yellow"]
)

# Bold Title
plt.title(
    "Distribution of Agricultural Records by Season",
    fontsize=20,
    fontweight="bold"
)

# Bold X and Y labels
plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Number of Records",
    fontsize=20,
    fontweight="bold"
)

# Bold tick labels
plt.xticks(fontsize=15, fontweight="bold")
plt.yticks(fontsize=15, fontweight="bold")

# Add values on top of bars
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{int(height)}",
        ha="center",
        va="bottom",
        fontsize=15,
        fontweight="bold"
    )

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that the Kharif season has the highest number of agricultural records (1,779), followed by Rabi (1,627), while Zaid has the lowest number of records (594). This indicates that the dataset has fewer observations for the Zaid season compared with Kharif and Rabi.

2. Average Yield by season Graph
"""

# Season-wise Average Yield

avg_yield = df.groupby("Season")["Yield_Tonnes_Ha"].mean()

plt.figure(figsize=(10, 6))

bars = plt.bar(
    avg_yield.index,
    avg_yield.values,
    color=["green", "red", "yellow", "violet"]
)

plt.title(
    "Average Crop Yield by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Yield (Tonnes/Ha)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(fontsize=20, fontweight="bold")
plt.yticks(fontsize=20, fontweight="bold")

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.2f}",
        ha="center",
        va="bottom",
        fontsize=20,
        fontweight="bold"
    )

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that the Kharif season has the highest average crop yield (5.63 tonnes/ha), followed by Rabi (5.04 tonnes/ha) and Zaid (4.64 tonnes/ha). This indicates that crop yield is higher in the Kharif season compared with Rabi and Zaid.

3. Season-wise Average Rainfall Graph
"""

# Season-wise Average Rainfall

avg_rainfall = df.groupby("Season")["Rainfall_mm"].mean()

plt.figure(figsize=(10, 6))

bars = plt.bar(
    avg_rainfall.index,
    avg_rainfall.values,
    color=["blue", "red", "orange", "purple"]
)

plt.title(
    "Average Rainfall by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Rainfall (mm)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(fontsize=20, fontweight="bold")
plt.yticks(fontsize=20, fontweight="bold")

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.2f}",
        ha="center",
        va="bottom",
        fontsize=20,
        fontweight="bold"
    )

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that the Kharif season has the highest average rainfall (849.20 mm), followed by Rabi (437.62 mm), while Zaid has the lowest average rainfall (304.65 mm). This indicates significant variation in rainfall across the three seasons.

4. Season-Wise Average Temperature
"""

# Season-wise Average Temperature

avg_temperature = df.groupby("Season")["Avg_Temperature_C"].mean()

plt.figure(figsize=(10, 6))

bars = plt.bar(
    avg_temperature.index,
    avg_temperature.values,
    color=["yellow", "green", "red", "blue"]
)

plt.title(
    "Average Temperature by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Temperature (°C)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(fontsize=20, fontweight="bold")
plt.yticks(fontsize=20, fontweight="bold")

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.2f}",
        ha="center",
        va="bottom",
        fontsize=20,
        fontweight="bold"
    )

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that the Zaid season has the highest average temperature (31.04°C), followed by Kharif (28.45°C), while Rabi has the lowest average temperature (23.49°C). This indicates a clear variation in average temperature across the three seasons.

5. Irrigation Method Distribution Graph
"""

# Irrigation Method Distribution

irrigation_counts = df["Irrigation_Method"].value_counts()

plt.figure(figsize=(9, 7))

plt.pie(
    irrigation_counts.values,
    labels=irrigation_counts.index,
    autopct="%1.1f%%",
    startangle=90,
    textprops={"fontsize":20, "fontweight": "bold"}
)

plt.title(
    "Distribution of Irrigation Methods",
    fontsize=20,
    fontweight="bold"
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows the distribution of irrigation methods used by farmers. Flood irrigation has the highest share at 32.8%, followed by rainfed farming at 26%. Drip irrigation accounts for 22.9%, while sprinkler irrigation has the lowest share at 18.4%.

6.crop wise Average Yield graph
"""

# Crop-wise Average Yield

avg_crop_yield = df.groupby("Crop")["Yield_Tonnes_Ha"].mean().sort_values(ascending=False)

plt.figure(figsize=(11, 7))

bars = plt.bar(
    avg_crop_yield.index,
    avg_crop_yield.values,
    color="seagreen"
)

plt.title(
    "Average Crop Yield by Crop",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel(
    "Crop",
    fontsize=14,
    fontweight="bold"
)

plt.ylabel(
    "Average Yield (Tonnes/Ha)",
    fontsize=14,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold",
    rotation=45,
    ha="right"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f"{height:.2f}",
        ha="center",
        va="bottom",
        fontsize=20,
        fontweight="bold"
    )

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows the average crop yield across different crops. Sugarcane has the highest average yield at 46.64 tonnes/ha, which is significantly higher than all other crops. Maize (2.71 tonnes/ha) and rice (2.43 tonnes/ha) follow, while pulses have the lowest yield at 0.92 tonnes/ha.

7.Rainfall vs Crop yield Graph
"""

# Rainfall vs Crop Yield

plt.figure(figsize=(10, 7))

plt.scatter(
    df["Rainfall_mm"],
    df["Yield_Tonnes_Ha"],
    alpha=0.6,
    s=45
)

plt.title(
    "Rainfall vs Crop Yield",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Rainfall (mm)",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Crop Yield (Tonnes/Ha)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(fontsize=20, fontweight="bold")
plt.yticks(fontsize=20, fontweight="bold")

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that crop yield generally increases with rainfall up to a moderate level. However, the data points are widely scattered, indicating that the relationship is not perfectly consistent. This suggests that rainfall influences crop yield, but other factors also contribute to variations in agricultural productivity.

8.Temperature vs crop yield graph
"""

# Temperature vs Crop Yield

plt.figure(figsize=(10, 7))

plt.scatter(
    df["Avg_Temperature_C"],
    df["Yield_Tonnes_Ha"],
    color="purple",
    alpha=0.6,
    s=45
)

plt.title(
    "Temperature vs Crop Yield",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Average Temperature (°C)",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Crop Yield (Tonnes/Ha)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows that crop yield is widely scattered across temperatures, with most observations concentrated around 20°C–35°C. Higher yields are mainly observed around 25°C–30°C, while yields tend to be lower at the extreme temperature ranges. Overall, the graph suggests that moderate temperatures are generally associated with better crop yields.

9. Season Wise Average Profit
"""

# Season-wise Average Profit

avg_profit = df.groupby("Season")["Profit_INR"].mean()

plt.figure(figsize=(10, 7))

plt.plot(
    avg_profit.index,
    avg_profit.values,
    marker="o",
    color="darkorange",
    linewidth=3,
    markersize=8
)

plt.title(
    "Average Profit by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Profit (INR)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

for x, y in zip(avg_profit.index, avg_profit.values):
    plt.text(
        x,
        y,
        f"{y:,.0f}",
        ha="center",
        va="bottom",
        fontsize=11,
        fontweight="bold"
    )

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""** Insight From This Graph**

This graph shows that the average profit is highest in the Kharif season (around ₹1.78 lakh), followed by Rabi (around ₹1 lakh). The Zaid season shows a negative average profit, indicating lower profitability compared with the other seasons. Overall, Kharif is the most profitable season in the graph.

10.Season wise Average Revenue Graph
"""

# Season-wise Average Revenue

avg_revenue = df.groupby("Season")["Revenue_INR"].mean()

plt.figure(figsize=(10, 7))

plt.plot(
    avg_revenue.index,
    avg_revenue.values,
    marker="o",
    color="royalblue",
    linewidth=3,
    markersize=8
)

plt.title(
    "Average Revenue by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Revenue (INR)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

for x, y in zip(avg_revenue.index, avg_revenue.values):
    plt.text(
        x,
        y,
        f"{y:,.0f}",
        ha="center",
        va="bottom",
        fontsize=11,
        fontweight="bold"
    )

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows that average revenue is highest in the Kharif season, decreases in the Rabi season, and is lowest in the Zaid season, indicating a clear downward trend in average revenue across the seasons.

11. water efficiency vs crop yield graph
"""

# Water Efficiency vs Crop Yield

plt.figure(figsize=(10, 7))

plt.scatter(
    df["Water_Efficiency_t_per_1000m3"],
    df["Yield_Tonnes_Ha"],
    color="green",
    alpha=0.6,
    s=45
)

plt.title(
    "Water Efficiency vs Crop Yield",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Water Efficiency (Tonnes per 1000 m³)",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Crop Yield (Tonnes/Ha)",
    fontsize=14,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows a positive relationship between water efficiency and crop yield, where crop yield generally increases as water efficiency improves. This indicates that efficient use of water can contribute to higher crop productivity.

12. Disease/pest Risk vs crop yield graph
"""

# Disease/Pest Risk vs Crop Yield

plt.figure(figsize=(10, 7))

plt.scatter(
    df["Disease_Pest_Risk_pct"],
    df["Yield_Tonnes_Ha"],
    color="crimson",
    alpha=0.6,
    s=45
)

plt.title(
    "Disease/Pest Risk vs Crop Yield",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel(
    "Disease/Pest Risk (%)",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Crop Yield (Tonnes/Ha)",
    fontsize=14,
    fontweight="bold"
)

plt.xticks(
    fontsize=18,
    fontweight="bold"
)

plt.yticks(
    fontsize=16,
    fontweight="bold"
)

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows that crop yield values are widely scattered across different Disease/Pest Risk (%) levels. There is no strong or clear relationship visible between disease/pest risk and crop yield, as high and low yields occur across a broad range of risk levels.

13. correlation Heatmap
"""

# Correlation Heatmap

numeric_df = df.select_dtypes(include="number")

correlation = numeric_df.corr()

plt.figure(figsize=(14, 10))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5
)

plt.title(
    "Correlation Heatmap of Agricultural Performance Variables",
    fontsize=18,
    fontweight="bold"
)

plt.xticks(
    fontsize=16,
    fontweight="bold",
    rotation=45,
    ha="right"
)

plt.yticks(
    fontsize=16,
    fontweight="bold",
    rotation=0
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows the correlation between different agricultural performance variables. Farm area has a strong positive relationship with production, while revenue, total cost, and profit are also strongly related to each other. Crop yield shows comparatively weaker relationships with most individual input factors. Overall, the heatmap indicates that farm size and financial variables have a stronger influence/association within the dataset than most other variables.

14. Season-wise Average Humidity graph
"""

# Season-wise Average Humidity

avg_humidity = df.groupby("Season")["Humidity_pct"].mean()

plt.figure(figsize=(10, 7))

plt.plot(
    avg_humidity.index,
    avg_humidity.values,
    marker="o",
    color="teal",
    linewidth=3,
    markersize=8
)

plt.title(
    "Average Humidity by Season",
    fontsize=20,
    fontweight="bold"
)

plt.xlabel(
    "Season",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Humidity (%)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

for x, y in zip(avg_humidity.index, avg_humidity.values):
    plt.text(
        x,
        y,
        f"{y:.2f}%",
        ha="center",
        va="bottom",
        fontsize=11,
        fontweight="bold"
    )

plt.grid(
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

The graph shows that the Kharif season has the highest average humidity at 71.41%, followed by Rabi at 58.09%, while Zaid has the lowest average humidity. This indicates a clear variation in humidity levels across the three seasons, with Kharif having substantially higher humidity than Rabi and Zaid.

15. Yield Distribution Graph
"""

# Yield Distribution

plt.figure(figsize=(10, 7))

plt.hist(
    df["Yield_Tonnes_Ha"].dropna(),
    bins=30,
    color="mediumseagreen",
    edgecolor="black",
    alpha=0.8
)

plt.title(
    "Distribution of Crop Yield",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel(
    "Crop Yield (Tonnes/Ha)",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Frequency",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows that most crop yield values are concentrated at the lower range (around 0–5 tonnes/ha), while only a small number of observations have much higher yields. The distribution has a strong right skew with a long tail extending toward higher crop yields, indicating the presence of a few high-yield observations.

**District Wise Average Crop Yield Graph**
"""

# District-wise Average Crop Yield

avg_district_yield = (
    df.groupby("District")["Yield_Tonnes_Ha"]
    .mean()
    .sort_values(ascending=False)
)

plt.figure(figsize=(12, 7))

plt.bar(
    avg_district_yield.index,
    avg_district_yield.values
)

plt.title(
    "Average Crop Yield by District",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel(
    "District",
    fontsize=20,
    fontweight="bold"
)

plt.ylabel(
    "Average Yield (Tonnes/Ha)",
    fontsize=20,
    fontweight="bold"
)

plt.xticks(
    fontsize=20,
    fontweight="bold",
    rotation=45,
    ha="right"
)

plt.yticks(
    fontsize=20,
    fontweight="bold"
)

for i, value in enumerate(avg_district_yield.values):
    plt.text(
        i,
        value,
        f"{value:.2f}",
        ha="center",
        va="bottom",
        fontsize=9,
        fontweight="bold"
    )

plt.grid(
    axis="y",
    linestyle="--",
    alpha=0.4
)

plt.tight_layout()
plt.show()

"""**Insight From This Graph**

This graph shows the average crop yield by district. Raikot has the highest average crop yield at 6.02 tonnes/ha, followed by Nalgonda (5.80) and Ludhiana (5.80). Erode has the lowest yield among the shown districts at 4.18 tonnes/ha. Overall, the graph indicates noticeable variation in crop yield across districts.

**Unusual patterns/outlier Analysis**
"""

# Outlier Analysis using IQR

Q1 = df['Yield_Tonnes_Ha'].quantile(0.25)
Q3 = df['Yield_Tonnes_Ha'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df['Yield_Tonnes_Ha'] < lower_bound) |
    (df['Yield_Tonnes_Ha'] > upper_bound)
]

print("Number of Yield Outliers:", len(outliers))
print(outliers[['Farm_ID', 'State', 'District', 'Crop', 'Season',
                 'Yield_Tonnes_Ha']])

"""**Statistical Techniques**"""

# Correlation Analysis

numeric_cols = [
    'Farm_Area_Hectares',
    'Rainfall_mm',
    'Avg_Temperature_C',
    'Humidity_pct',
    'Soil_Moisture_pct',
    'Nitrogen_kg_ha',
    'Phosphorus_kg_ha',
    'Potassium_kg_ha',
    'Fertilizer_kg_ha',
    'Pesticide_Litre_ha',
    'Seed_Quality_Score',
    'Yield_Tonnes_Ha',
    'Water_Used_m3',
    'Water_Efficiency_t_per_1000m3'
]

correlation = df[numeric_cols].corr()

print(correlation)

# ANOVA: Yield across different Seasons

from scipy.stats import f_oneway

kharif = df[df['Season'] == 'Kharif']['Yield_Tonnes_Ha']
rabi = df[df['Season'] == 'Rabi']['Yield_Tonnes_Ha']
zaid = df[df['Season'] == 'Zaid']['Yield_Tonnes_Ha']

f_stat, p_value = f_oneway(kharif, rabi, zaid)

print("F-statistic:", f_stat)
print("P-value:", p_value)

"""**Graph wise Insights**

 graph 1

This graph shows the distribution of agricultural records across different seasons. Kharif has the highest number of records (1,779), followed by Rabi (1,627), while Zaid has the lowest (594). This indicates that the dataset has substantially more agricultural records for Kharif and Rabi seasons compared with the Zaid season.



Graph 2

This graph shows the average crop yield across different seasons. Kharif has the highest average crop yield (5.63 tonnes/ha), followed by Rabi (5.04 tonnes/ha), while Zaid has the lowest (4.64 tonnes/ha). This indicates that crop yield is highest during the Kharif season and gradually decreases across Rabi and Zaid seasons.

Graph 3

This graph shows that Kharif has the highest average rainfall (849.20 mm), followed by Rabi (437.62 mm), while Zaid has the lowest average rainfall (304.65 mm). This indicates a clear seasonal variation in rainfall, with Kharif receiving substantially more rainfall than the other seasons.

Graph 4

This graph shows the average temperature across different seasons. Zaid has the highest average temperature (31.04°C), followed by Kharif (28.45°C), while Rabi has the lowest (23.49°C). This indicates that temperature varies considerably by season, with Zaid being the warmest and Rabi the coolest season.



Graph 5

This graph shows the distribution of irrigation methods used in agriculture. Flood irrigation has the highest share (32.8%), followed by Rainfed (26.0%), Drip (22.9%), and Sprinkler (18.4%). This indicates that Flood irrigation is the most commonly represented method, while Sprinkler irrigation has the smallest share in the dataset.







Graph 6

This graph shows the average crop yield for different crops. Sugarcane has the highest average yield (46.64 tonnes/ha), followed by Maize (2.71 tonnes/ha) and Rice (2.43 tonnes/ha), while Pulses has the lowest average yield (0.92 tonnes/ha). This indicates a substantial difference in productivity among different crops.

Graph 7

This graph shows the relationship between rainfall and crop yield. Crop yield generally tends to increase with rainfall up to a moderate level, but the data points are widely scattered. This indicates that rainfall influences crop yield, although other agricultural and environmental factors also play an important role.

Graph 8

This graph shows the relationship between temperature and crop yield. Higher crop yields are mainly observed around the moderate temperature range of 25°C – 30°C, while lower yields are also visible at extreme temperature levels. This indicates that suitable temperature conditions may support better crop productivity.

Graph 9

This graph shows the variation in average profit across different seasons. Kharif has the highest average profit at around ₹1.78 lakh, followed by Rabi at around ₹1 lakh, while Zaid shows a negative average profit. This indicates that Kharif is the most profitable season in the dataset, whereas Zaid has comparatively poor profitability.

Graph 10

This graph shows the variation in average revenue across different seasons. Kharif has the highest average revenue, followed by Rabi, while Zaid has the lowest average revenue. This indicates that agricultural revenue is comparatively stronger during Kharif and weaker during Zaid.

Graph 11

This graph shows the relationship between water efficiency and crop yield. Crop yield generally increases as water efficiency improves, although some variation is present in the observations. This indicates that efficient utilization of water can contribute to improved agricultural productivity.

Graph 12

This graph shows the relationship between disease/pest risk and crop yield. The yield values are widely scattered across different disease/pest risk levels, with both high and low yields appearing at different risk levels. This indicates that there is no strong or clear relationship between disease/pest risk and crop yield in the dataset.

Graph 13

This graph shows the correlations among different agricultural variables. Farm area has a strong positive relationship with production, while revenue, total cost, and profit also show strong relationships with each other. This indicates that farm size and financial factors are closely associated with agricultural production and profitability.

Graph 14

The graph shows that the Kharif season has the highest average humidity at 71.41%, followed by Rabi at 58.09%, while Zaid has the lowest average humidity. This indicates a clear variation in humidity levels across the three seasons, with Kharif having substantially higher humidity than Rabi and Zaid.

Graph 15

This graph shows the distribution of crop yield values across the agricultural records. Most yield values are concentrated around 0–5 tonnes/ha, while only a small number of observations have considerably higher yields. This indicates that the yield distribution is strongly right-skewed, with a few high-yield observations.

**Key Findings**

Kharif season shows the strongest overall agricultural performance, with the highest number of agricultural records, average crop yield, rainfall, profit, and revenue compared with Rabi and Zaid.

Crop yield varies considerably across seasons and crops. Kharif has the highest seasonal average yield, while Sugarcane has a much higher average yield than the other crops, and Pulses has the lowest average yield.

Rainfall and temperature show clear seasonal variation. Kharif receives substantially more rainfall, while Zaid has the highest average temperature and Rabi has the lowest.

Flood irrigation is the most commonly represented irrigation method in the dataset, while Sprinkler irrigation has the smallest share.

Rainfall and temperature have an observable association with crop yield, but the scattered data points indicate that crop yield is influenced by multiple agricultural and environmental factors.

Water efficiency is positively associated with crop yield, indicating that better utilization of water can contribute to improved agricultural productivity.

Kharif is the most profitable season, with the highest average profit and revenue, whereas Zaid shows comparatively weaker financial performance and negative average profit.

Disease/pest risk does not show a strong or clear relationship with crop yield in the dataset, as both high and low yields occur across different risk levels.

Farm area and financial variables are strongly associated with agricultural performance. Farm area has a strong positive relationship with production, while revenue, total cost, and profit show strong relationships with each other.

Humidity also varies considerably across seasons, with Kharif having the highest average humidity and Zaid having the lowest.
Crop yield distribution is strongly right-skewed, with most observations concentrated around 0–5 tonnes/ha and only a small number of observations showing considerably higher yields.

**Conclusion**

The Seasonal Agriculture Performance Analysis project demonstrates that agricultural performance varies across different seasons, farming conditions, resource usage, and environmental factors. By exploring and visualizing the agricultural dataset, the project identified important seasonal patterns, differences, relationships, and variations in agricultural performance.

The analysis shows that factors such as seasonal conditions, irrigation practices, resource utilization, crop production, and economic outcomes are important when evaluating agricultural performance. Comparing these factors across seasons provides a clearer understanding of how agricultural activities and outcomes change under different conditions.

Overall, the project demonstrates how data analytics and visualization can transform raw agricultural data into meaningful insights. These insights can help in understanding seasonal agricultural patterns and support evidence-based decision-making and better seasonal agricultural planning.

**Recommendations**

**Adopt season-specific farming strategies**

Farming practices should be planned according to the conditions of Kharif, Rabi, and Zaid seasons rather than following the same approach throughout the year.

**Improve irrigation management**

Since irrigation methods show noticeable differences, farmers should focus on efficient water-management practices and select suitable irrigation methods according to crop and seasonal requirements.

**Optimize water usage**

Water availability and usage should be monitored carefully, particularly during seasons with lower rainfall, to improve resource efficiency.

**Select crops according to seasonal conditions**

Crop selection should consider factors such as rainfall, temperature, water availability, and expected yield for the particular season.

**Use data-driven agricultural planning**

Historical agricultural data should be analyzed regularly to identify seasonal patterns and support better decisions about crops, resources, and farming practices.


**Monitor production and economic performance together**

Farmers and stakeholders should consider both crop yield and economic outcomes when evaluating farming practices, instead of focusing on production alone.

**Continue monitoring seasonal variations**

Agricultural performance should be tracked across seasons and regions so that unusual patterns or areas requiring further investigation can be identified early.

 **Overall Recommendation**

Season-specific planning, efficient resource utilization, appropriate irrigation practices, and data-driven decision-making should be encouraged to improve agricultural performance and support sustainable seasonal agricultural planning.

**Project Final Summary**

This project analyzed agricultural data across different seasons to understand variations in agricultural performance. Data exploration and visualization were used to identify important patterns, trends, relationships, and differences.

The analysis considered factors such as seasonal conditions, crop production, resource usage, irrigation practices, and economic performance. The identified findings helped in understanding how agricultural performance changes across different conditions.

The project demonstrates how data analytics can be used to convert raw agricultural data into meaningful insights and support evidence-based agricultural planning and decision-making.
"""